services:
  - type: web
    plan: free
    name: s
    runtime: python
    repo: https://github.com/5uperb0y/url-shortener.git
    region: singapore
    buildCommand: './build.sh'
    startCommand: './run.sh'
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: 'url_shortener.settings'
      - key: DATABASE_URL
        fromDatabase:
          name: shortener-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shortener-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: shortener-redis
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
  - type: redis
    name: shortener-redis
    plan: free
    region: singapore
    ipAllowList: []
    maxmemoryPolicy: noeviction
databases:
  - name: shortener-db
    plan: free
    region: singapore